import ROOT as r
import numpy as np
from time import sleep
from QuadraticFit import *

r.gROOT.SetBatch(True)
r.gStyle.SetOptStat(0000)
r.gROOT.ForceStyle()

def plotMJJUncertainties(inputFile,outputFile,tag):
    rFile = r.TFile.Open(inputFile)
    c = r.TCanvas("","",2000,2000)

    c.Divide(2,2)
    uncs = ["jes","jer","jms","jmr"]
    c.cd(1)
    hjesNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjesUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jesUp".format(tag))
    hjesDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jesDown".format(tag))

    hjesNom.SetTitle("JES")
    hjesUp.SetLineColor(r.kGreen)
    hjesDn.SetLineColor(r.kRed)
    hjesNom.ProjectionY().Draw()
    hjesUp.ProjectionY().Draw("same")
    hjesDn.ProjectionY().Draw("same")
    legendjes = r.TLegend(0.7, 0.7, .85, .85)
    legendjes.AddEntry(hjesNom,"nominal","l")
    legendjes.AddEntry(hjesUp,"1sigma up","l")
    legendjes.AddEntry(hjesDn,"1sigma down","l")

    legendjes.Draw()

    c.cd(2)
    hjerNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjerUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jerUp".format(tag))
    hjerDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jerDown".format(tag))

    hjerNom.SetName("nom_JER")
    hjerNom.SetTitle("JER")
    hjerUp.SetLineColor(r.kGreen)
    hjerDn.SetLineColor(r.kRed)
    hjerNom.ProjectionY().Draw()
    hjerUp.ProjectionY().Draw("same")
    hjerDn.ProjectionY().Draw("same")
    legendjer = r.TLegend(0.7, 0.7, .85, .85)
    legendjer.AddEntry(hjerNom,"nominal","l")
    legendjer.AddEntry(hjerUp,"1sigma up","l")
    legendjer.AddEntry(hjerDn,"1sigma down","l")

    legendjer.Draw()

    c.cd(3)
    hjmsNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjmsUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jmsUp".format(tag))
    hjmsDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jmsDown".format(tag))
    
    hjmsNom.SetName("nom_JMS")
    hjmsNom.SetTitle("JMS")
    hjmsUp.SetLineColor(r.kGreen)
    hjmsDn.SetLineColor(r.kRed)
    hjmsNom.ProjectionY().Draw()
    hjmsUp.ProjectionY().Draw("same")
    hjmsDn.ProjectionY().Draw("same")
    legendjms = r.TLegend(0.7, 0.7, .85, .85)
    legendjms.AddEntry(hjmsNom,"nominal","l")
    legendjms.AddEntry(hjmsUp,"1sigma up","l")
    legendjms.AddEntry(hjmsDn,"1sigma down","l")

    legendjms.Draw()

    c.cd(4)
    hjmrNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjmrUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jmrUp".format(tag))
    hjmrDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jmrDown".format(tag))

    hjmrNom.SetName("nom_JMR")
    hjmrNom.SetTitle("JMR")
    hjmrUp.SetLineColor(r.kGreen)
    hjmrDn.SetLineColor(r.kRed)
    hjmrNom.ProjectionY().Draw()
    hjmrUp.ProjectionY().Draw("same")
    hjmrDn.ProjectionY().Draw("same")
    legendjmr = r.TLegend(0.7, 0.7, .85, .85)
    legendjmr.AddEntry(hjmrNom,"nominal","l")
    legendjmr.AddEntry(hjmrUp,"1sigma up","l")
    legendjmr.AddEntry(hjmrDn,"1sigma down","l")

    legendjmr.Draw()

    c.SaveAs(outputFile)


def plotMJYUncertainties(inputFile,outputFile,tag):
    rFile = r.TFile.Open(inputFile)
    c = r.TCanvas("","",2000,2000)

    c.Divide(2,2)
    uncs = ["jes","jer","jms","jmr"]
    c.cd(1)
    hjesNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjesUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jesUp".format(tag))
    hjesDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jesDown".format(tag))

    hjesNom.SetTitle("JES")
    hjesUp.SetLineColor(r.kGreen)
    hjesDn.SetLineColor(r.kRed)
    hjesNom.ProjectionX().Draw()
    hjesUp.ProjectionX().Draw("same")
    hjesDn.ProjectionX().Draw("same")
    legendjes = r.TLegend(0.7, 0.7, .85, .85)
    legendjes.AddEntry(hjesNom,"nominal","l")
    legendjes.AddEntry(hjesUp,"1sigma up","l")
    legendjes.AddEntry(hjesDn,"1sigma down","l")

    legendjes.Draw()

    c.cd(2)
    hjerNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjerUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jerUp".format(tag))
    hjerDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jerDown".format(tag))

    hjerNom.SetName("nom_JER")
    hjerNom.SetTitle("JER")
    hjerUp.SetLineColor(r.kGreen)
    hjerDn.SetLineColor(r.kRed)
    hjerNom.ProjectionX().Draw()
    hjerUp.ProjectionX().Draw("same")
    hjerDn.ProjectionX().Draw("same")
    legendjer = r.TLegend(0.7, 0.7, .85, .85)
    legendjer.AddEntry(hjerNom,"nominal","l")
    legendjer.AddEntry(hjerUp,"1sigma up","l")
    legendjer.AddEntry(hjerDn,"1sigma down","l")

    legendjer.Draw()

    c.cd(3)
    hjmsNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjmsUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jmsUp".format(tag))
    hjmsDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jmsDown".format(tag))
    
    hjmsNom.SetName("nom_JMS")
    hjmsNom.SetTitle("JMS")
    hjmsUp.SetLineColor(r.kGreen)
    hjmsDn.SetLineColor(r.kRed)
    hjmsNom.ProjectionX().Draw()
    hjmsUp.ProjectionX().Draw("same")
    hjmsDn.ProjectionX().Draw("same")
    legendjms = r.TLegend(0.7, 0.7, .85, .85)
    legendjms.AddEntry(hjmsNom,"nominal","l")
    legendjms.AddEntry(hjmsUp,"1sigma up","l")
    legendjms.AddEntry(hjmsDn,"1sigma down","l")

    legendjms.Draw()

    c.cd(4)
    hjmrNom = rFile.Get("TTbar_mJY_mJJ_{0}_nom".format(tag))
    hjmrUp  = rFile.Get("TTbar_mJY_mJJ_{0}_jmrUp".format(tag))
    hjmrDn  = rFile.Get("TTbar_mJY_mJJ_{0}_jmrDown".format(tag))

    hjmrNom.SetName("nom_JMR")
    hjmrNom.SetTitle("JMR")
    hjmrUp.SetLineColor(r.kGreen)
    hjmrDn.SetLineColor(r.kRed)
    hjmrNom.ProjectionX().Draw()
    hjmrUp.ProjectionX().Draw("same")
    hjmrDn.ProjectionX().Draw("same")
    legendjmr = r.TLegend(0.7, 0.7, .85, .85)
    legendjmr.AddEntry(hjmrNom,"nominal","l")
    legendjmr.AddEntry(hjmrUp,"1sigma up","l")
    legendjmr.AddEntry(hjmrDn,"1sigma down","l")

    legendjmr.Draw()

    c.SaveAs(outputFile)

#SR
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_VRT_MJY_TT_unc.png","VRT")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_VRT_MJJ_TT_unc.png","VRT")
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_VRL_MJY_TT_unc.png","VRL")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_VRL_MJJ_TT_unc.png","VRL")
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_TT_MJY_TT_unc.png","TT")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_TT_MJJ_TT_unc.png","TT")
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_TT_MJY_TT_unc.png","ATT")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_TT_MJJ_TT_unc.png","ATT")
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_LL_MJY_TT_unc.png","LL")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_LL_MJJ_TT_unc.png","LL")
plotMJYUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_LL_MJY_TT_unc.png","AT")
plotMJJUncertainties("templates/WP_0.8_0.95/2016/TTbar.root","2016_LL_MJJ_TT_unc.png","AT")

plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_VRT_MJY_TT_unc.png","VRT")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_VRT_MJJ_TT_unc.png","VRT")
plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_VRL_MJY_TT_unc.png","VRL")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_VRL_MJJ_TT_unc.png","VRL")
plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_TT_MJY_TT_unc.png","TT")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_TT_MJJ_TT_unc.png","TT")
plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_TT_MJY_TT_unc.png","ATT")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_TT_MJJ_TT_unc.png","ATT")
plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_LL_MJY_TT_unc.png","LL")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_LL_MJJ_TT_unc.png","LL")
plotMJYUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_LL_MJY_TT_unc.png","AT")
plotMJJUncertainties("templates/WP_0.8_0.95/2017/TTbar.root","2017_LL_MJJ_TT_unc.png","AT")

plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_VRT_MJY_TT_unc.png","VRT")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_VRT_MJJ_TT_unc.png","VRT")
plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_VRL_MJY_TT_unc.png","VRL")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_VRL_MJJ_TT_unc.png","VRL")
plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_TT_MJY_TT_unc.png","TT")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_TT_MJJ_TT_unc.png","TT")
plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_TT_MJY_TT_unc.png","ATT")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_TT_MJJ_TT_unc.png","ATT")
plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_LL_MJY_TT_unc.png","LL")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_LL_MJJ_TT_unc.png","LL")
plotMJYUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_LL_MJY_TT_unc.png","AT")
plotMJJUncertainties("templates/WP_0.8_0.95/2018/TTbar.root","2018_LL_MJJ_TT_unc.png","AT")